### ISSUE TITLE
Push a 2.0.1 release

### ISSUE THREAD

**Issue by TysonAndre** [igbinary/igbinary#110]
Release this to fix https://github.com/igbinary/igbinary/issues/103 (issue discovered after the 2.0.0 release tag)
https://github.com/igbinary/igbinary/pull/109 finishes changing the package.xml tags. After that is merged, push a tag for 2.0.1, create a github release, and create a pecl release.

In the release (https://github.com/igbinary/igbinary/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc):

- Stop checking for apc in php 7 builds: https://github.com/igbinary/igbinary/pull/108
- Add 7.1 to Travis CI, exclude some matrix entries  (unrelated): 
- Fix session.decode_handler=igbinary not calling __wakeup(): https://github.com/igbinary/igbinary/pull/106
- Add myself to package.xml : https://github.com/igbinary/igbinary/pull/104
- Reuse created zend_string instance when unserializing (https://github.com/igbinary/igbinary/pull/81)

**Comment by phadej** [comment]
Before this, seems windows build failed in the cloud:
```
Filename: igbinary-2.0.0.tgz
Build type: release

For each build combination and status please refer to the list below.


php_igbinary-2.0.0-7.0-nts-vc14-x64 failed

php_igbinary-2.0.0-7.0-ts-vc14-x64 failed

php_igbinary-2.0.0-7.0-nts-vc14-x86 failed

php_igbinary-2.0.0-7.0-ts-vc14-x86 failed
```

have you any idea what may caused it?

**Comment by phadej** [comment]
Ok, I see, windows might be fixed. I'll do a release

**Comment by kn007** [comment]
Nice work!

**Comment by mente** [comment]
Looks like it wasn't released :-/

**Comment by TysonAndre** [comment]
Updated https://github.com/igbinary/igbinary/releases/tag/2.0.1 to fix `pecl install`. Also forgot one place to check for php5 when trying to support APC(not APCu)

https://github.com/igbinary/igbinary/pull/112

**Comment by phadej** [comment]
@TysonAndre please don't retag in the future, that's very bad practice. If there's some mistake, then just do another bump.

**Comment by TysonAndre** [comment]
Ok. That was limited to bug fixes before the pecl release existed, but I'll stop doing that.

Is anything blocking releasing 2.0.1?

**Comment by jeffreyddavis** [comment]
Any chance we might get the working dll soon? It looks like it is ready :)

**Comment by phadej** [comment]
I'll upload package tomorrow

**Comment by jeffreyddavis** [comment]
Great. Thank you for your work. I can't wait to see this run on php 7 :)

**Comment by phadej** [comment]
Done. Had to remove @TysonAndre from xml file as PECL doesn't accept such xml otherwise.

http://pecl.php.net/package/igbinary/2.0.1

**Comment by jeffreyddavis** [comment]
I was able to compile a TS and NTS x86 DLL version of this. Not sure if you would want that. I have it working with PHP7.0.8

**Comment by jeffreyddavis** [comment]
My testing shows a 20% speed improvement using igbinary with php7 (over native serialize with php7)
