### ISSUE TITLE
Release igbinary 2.0.2, 2.0.3 to pecl

### ISSUE THREAD

**Issue by TysonAndre** [igbinary/igbinary#122]
Need to merge https://github.com/igbinary/igbinary/pull/121 to master first.

Also, are any of the other igbinary maintainers able to sponsor me for a PECL account request?

**Comment by lt** [comment]
@TysonAndre Have you followed the account request procedure yet? (https://pecl.php.net/account-request.php)

@pierrejoye As you're both lead on this extension _and_ a PECL admin, would be willing to approve Tysons addition to the package? He seems to be doing most of the work lately and it would be great to get the PHP 7.1 compatible versions up.

**Comment by tricky** [comment]
I can naturally add to the igbinary list, but it appears there's no account yet?

**Comment by remicollet** [comment]
How can I help ?

**Comment by TysonAndre** [comment]
I requested and obtained a git account, which was required before requesting a PECL account.

- I forgot the git account's password, which seems like it might be necessary for some tasks. I can't find a working link to reset the password.
- The password reset link on master.php.net doesn't work, emailing group@php.net to ask about resetting the git account password didn't work either

I could request a PECL account linking to this issue, and mentioning @remicollet / @tricky as sponsors.

**Comment by TysonAndre** [comment]
I requested a PECL account

**Comment by TysonAndre** [comment]
@rlerdorf I created a PECL account request, could you look at it? https://marc.info/?l=pecl-dev&m=149921032907984&w=2

(Continuing thread in https://marc.info/?l=pecl-dev&m=148526655621438&w=2)

**Comment by rlerdorf** [comment]
I created the account, and the password reset is at https://master.php.net/forgot.php

**Comment by TysonAndre** [comment]
The step is to be added to igbinary lead developers (See https://github.com/igbinary/igbinary/issues/122#issuecomment-293565948 by @tricky) . After logging in and viewing https://pecl.php.net/release-upload.php :


> ERROR:

> -    You are not registered as lead developer for any packages.

> Upload a new package distribution file built using "pear package" here. The information from your package.xml file will be displayed on the next screen for verification. The maximum file size is 16 MB.

> Uploading new releases is restricted to each package's lead developer(s).

**Comment by rlerdorf** [comment]
ok, added as lead

**Comment by TysonAndre** [comment]
Thanks!

**Comment by TysonAndre** [comment]
Done, but windows DLLs aren't built for 2.0.2-2.0.4 at the time of writing. Created #143
