### ISSUE TITLE
Create a major 3.0 release, dropping support for apc and php 5

### ISSUE THREAD

**Issue by TysonAndre** [igbinary/igbinary#153]
Current plan: continue to backport bug fixes to 2.0, but not new features.

- Release a patch version with changes on master first
- Move src/php7 to root directory, updating package.xml
- Continue keeping src/php5 and src/php7 in the 2.x releases.
- Keep APCu support
- Change constraint in package.xml to php >= 7.0 for the 3.x releases

Motivation:

- https://github.com/igbinary/igbinary/issues/143
- https://github.com/igbinary/igbinary/issues/50
- Faster to finish unit tests if travis.yml has fewer entries
- PHP 5.6 is finished active support, security support will end in december 2018 

EDIT: Other tickets to include:

- [x] https://github.com/igbinary/igbinary/issues/64

**Comment by TysonAndre** [comment]
cc @phadej @pierrejoye @tricky @tsavola @tuner

**Comment by tricky** [comment]
Excellent, this seems fine by me. I might keep the php7 dir, after all php 8 is a mere three years away. 😄  Not feeling too strongly though.

**Comment by phadej** [comment]
:+1:

**Comment by TysonAndre** [comment]
Current status:

- The v2 branch will work poorly/incorrectly in php 7.4-dev after the typed properties v2 RFC was merged. Releasing 2.0.9 with a maximum version of PHP 7.3 (after 3.0.0 is released) may help avoid confusion.
- There's still more work needed for typed property support (only in php7.4 when user defined classes (and possibly internal?) use typed properties). See #153. If it's easy enough, that will be part of 3.0.0. Otherwise, it'd be in a later minor release.
- Need to write release notes
