### ISSUE TITLE
Using the extension without session in windows builds

### ISSUE THREAD

**Issue by dktapps** [igbinary/igbinary#163]
It appears that the current PHP 7 version has a hard dependency on the `session` extension that cannot be disabled via command-line options during configuration. This is particularly inconvenient as I don't use `session` in my projects and would like to make use of this extension without its `session` capabilities, but the `session` extension must be compiled statically, necessitating a full recompile of PHP.

PHP: 7.2.1 x64 (Windows) without session
igbinary: 2.0.5

**Comment by TysonAndre** [comment]
```
  AC_DEFINE('HAVE_IGBINARY', 1, 'Have igbinary support', false);
  ADD_EXTENSION_DEP('igbinary', 'session');
  PHP_INSTALL_HEADERS('ext/igbinary', 'igbinary.h php_igbinary.h ' + subdir + '\\igbinary.h ' + subdir + '\\php_igbinary.h');
}
```

https://github.com/igbinary/igbinary/blob/master/config.w32

It unconditionally depends on session right now.

One solution would be to add a flag to disable Igbinary session for Windows, and build Igbinary without it.

- would also need to set cflags to indicate to not use session in windows builds

You could use https://github.com/igbinary/igbinary/blob/master/WINDOWS.md
