### ISSUE TITLE
Unserialize in Java

### ISSUE THREAD

**Issue by shinegin** [igbinary/igbinary#167]
Any plans on other language support ? like Java ...

**Comment by TysonAndre** [comment]
Not at the moment, something like protobuf or msgpack (For binary protocols) or json (For human readable protocols) might be more suitable, and have support for a wider variety of programming languages. You'd potentially still have some issues with serialize()/__wakeup().

I'd imagine there'd need to be an `igbinary.PHPObject{className: string, otherFields:HashMap<string,Object>}` and `igbinary.PHPArray` (with an ordered list of key-value pairs) and possibly `igbinary.PHPReference` in many languages.

- As well as a way of associating custom serialization and unserialization methods for java (or other language's objects)
- I'd imagine there'd be some issues with usability, etc, and having a practical way to serialize objects in Java that can be used by PHP. (Maybe some way to associative java class names with a specific php class names for serializing/unserializing in java)

If anyone looking at this interested:
https://github.com/TysonAndre/igbinary-hhvm exists for HHVM as a port to a slightly different PHP implementation.

**Comment by shinegin** [comment]
I see. Thank you for your responsible answer.
