### ISSUE TITLE
Fix build failure for php 7.3-dev (GC_CFLAGS can't be modified by serializer)

### ISSUE THREAD

**Issue by TysonAndre** [igbinary/igbinary#172]
See what php/php-src's `ext/standard/*serialize*` is doing in php 7.3-dev for unserialize

Also check https://github.com/php/php-src/blob/master/UPGRADING.INTERNALS for php 7.3 (I haven't looked at it yet)

**Comment by sodabrew** [comment]
Hi! I just bumped into this while adding PHP 7.3 (master) to the matrix for php-memcached.
