### ISSUE TITLE
What is the performance gain?

### ISSUE THREAD

**Issue by Webonaute** [igbinary/igbinary#184]
I know igbinary was giving lot of advantage on PHP5.

But I can't find any benchmark with PHP7.

anyone can light up my lantern?

**Comment by TysonAndre** [comment]
You can install and run https://github.com/igbinary/igbinary/blob/master/benchmark/run-bench.php locally (after installing and enabling igbinary) to get benchmark results.

**Comment by TysonAndre** [comment]
For me, unserialization is around twice as fast. (Depends on the objects being used)

If compact_strings is turned on, serialization is slightly slower than serialize() (And serialization is faster with compact_strings turned off)

**Comment by TysonAndre** [comment]
https://blobfolio.com/2017/03/benchmark-php7-serialization/ is one comparison I found online.
It's from March 19th, and predates some optimizations that were added since then.

**Comment by shawnlindstrom** [comment]
Here's another comparison under PHP 7.2.15 and Laravel 5.7.25: https://medium.com/@akalongman/phpredis-vs-predis-comparison-on-real-production-data-a819b48cbadb
