### ISSUE TITLE
Testsuite failing after build of version 2.0.6

### ISSUE THREAD

**Issue by chrbayer** [igbinary/igbinary#189]
After building version 2.0.6 or master on by Arch Linux box using gcc (GCC) 8.1.1 20180531, the testsuite fails in these two tests:

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Resource [tests/igbinary_023.phpt]
igbinary session decoder should call __wakeup [tests/igbinary_061.phpt]
=====================================================================

The test log and the phpinfo log are attached.

[phpinfo.log](https://github.com/igbinary/igbinary/files/2107530/phpinfo.log)
[test.log](https://github.com/igbinary/igbinary/files/2107531/test.log)

**Comment by TysonAndre** [comment]
The files you included don't include any details on why they failed. I'm guessing that there's an issue with your build process being able to create files in /tmp or something along those lines. It's probably harmless.

You can show tests on standard output with 

- `make test TESTS="--show-diff"`

Or upload the corresponding tests/igbinary_023.out and  `tests/igbinary_061.out` files that were generated by `make test`

**Comment by chrbayer** [comment]
There should be no problem writing on /tmp, permissions and free space should be Ok..

Here is content of the requested files:

igbinary_023.out:

resource
04
FAIL

Warning: fclose() expects parameter 1 to be resource, boolean given in /home/chrbayer/igbinary/tests/igbinary_023.php on line 17

igbinary_061.out:

Warning: session_start(): open(/run/httpd/tmp/sess_h0okqblclm0acgkngraglj5a01, O_RDWR) failed: Permission denied (13) in /home/chrbayer/igbinary/tests/igbinary_061.php on line 13

Warning: session_start(): Failed to read session data: files (path: /run/httpd/tmp) in /home/chrbayer/igbinary/tests/igbinary_061.php on line 13
int(1234567890)

Warning: session_decode(): Session is not active. You cannot decode session data in /home/chrbayer/igbinary/tests/igbinary_061.php on line 22
bool(false)

Notice: Undefined index: date in /home/chrbayer/igbinary/tests/igbinary_061.php on line 23

Fatal error: Uncaught Error: Call to a member function getTimestamp() on null in /home/chrbayer/igbinary/tests/igbinary_061.php:23
Stack trace:
#0 {main}
  thrown in /home/chrbayer/igbinary/tests/igbinary_061.php on line 23

This is indeed a problem with the permission, if I build and run with http user, this should work.
