### ISSUE TITLE
Explain error message

### ISSUE THREAD

**Issue by tobiase** [igbinary/igbinary#206]
What does igbinary_unserialize_long: end-of-data mean?

**Comment by tricky** [comment]
It means igbinary ran out of data while unserializing a long. Most likely truncated data.

**Comment by tobiase** [comment]
@tricky Do you have any idea, how I can solve this?

**Comment by tricky** [comment]
I would suggest you take the raw data and look at it closely.

You're probably storing the data somewhere, so try to compare the serialized string while storing with the data you receive from storage. Could be a storage max length issue or some such.

**Comment by tobiase** [comment]
Thank your very much, that helped.
After increasing the column size, the error vanished.
