### ISSUE TITLE
undefined symbol: _zval_ptr_dtor in php 7.3.0

### ISSUE THREAD

**Issue by schferbe** [igbinary/igbinary#218]
I am using version 2.0.8 of igbinary on my raspberry pi. `$ uname -a
Linux raspberrypi 4.14.86-1-ARCH #1 SMP Fri Dec 7 01:48:56 UTC 2018 armv7l GNU/Linux`

After an upgrade of php and php-fpm from 7.2.13 to 7.3.0 I get the following error:
`$ php -m 
PHP Warning:  PHP Startup: Unable to load dynamic library 'igbinary.so' (tried: /usr/lib/php/modules/igbinary.so (/usr/lib/php/modules/igbinary.so: undefined symbol: _zval_ptr_dtor), /usr/lib/php/modules/igbinary.so.so (/usr/lib/php/modules/igbinary.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

Can you please give me a pointer how I can resolve this?

**Comment by francoisfreitag** [comment]
Did you rebuild `php-igbinary` after the upgrade to PHP 7.3?

**Comment by schferbe** [comment]
@francoisfreitag thanks! That was too obvious...

**Comment by pathros** [comment]
@francoisfreitag  How do you rebuild? [I got the same error](https://stackoverflow.com/q/68645549/1883256) when trying to install sqlsrv extensions on Ubuntu 20.04.2 (Laravel Homestead) for a Symfony 4.2 app

**Comment by francoisfreitag** [comment]
It depends on your extension. For igbinary, the steps are outlined in https://github.com/igbinary/igbinary#building-from-source.
