### ISSUE TITLE
How can php-redis support igbinary on WINDOWS?

### ISSUE THREAD

**Issue by Planeptune** [igbinary/igbinary#219]
I'm using PHP7.0 on WINDOWS and I'm trying to install redis and igbinary for it. Now my phpinfo() shows that redis is ready to use but there is no igbinary in serializers:
![image](https://user-images.githubusercontent.com/20297699/50091332-0e285000-0246-11e9-95b1-6ce5df8f8ea5.png)

But phpinfo() also shows that igbinary is ready to use too:
![image](https://user-images.githubusercontent.com/20297699/50091378-2e580f00-0246-11e9-83eb-bdae2ece5870.png)

And I'm sure igbinary is loaded before redis... ,probably:
![image](https://user-images.githubusercontent.com/20297699/50091424-5a739000-0246-11e9-8d2f-fb01b645af62.png)

How can I make php-redis surpport using igbinary on WINDOWS? Surely I know one way to solve this problem is to use Ubuntu... but NO! I want to work on WINDOWS...

**Comment by jpwuwujp** [comment]
菜的抠脚

**Comment by TysonAndre** [comment]
You'd have to build the redis module from source.

See https://github.com/igbinary/igbinary/blob/master/WINDOWS.md

If you download redis similarly to the way those instructions mention apcu, configure --help should mention --enable-redis-igbinary as an additional option. If you enable that, redis will be able to use igbinary (and will fail to load if igbinary is not loaded).

This is a design choice by the redis maintainers. Different magic bytes are chosen by that redis extension to indicate which serializer was used to serializer the data.

**Comment by Planeptune** [comment]
> You'd have to build the redis (and igbinary) module from source.
> 
> See https://github.com/igbinary/igbinary/blob/master/WINDOWS.md
> 
> If you download redis similarly to the way those instructions mention apcu, configure --help should mention --enable-redis-igbinary as an additional option. If you enable that, redis will be able to use igbinary (and will fail to load if igbinary is not loaded).
> 
> This is a design choice by the redis maintainers. Different magic bytes are chosen by that redis extension to indicate which serializer was used to serializer the data.

I try to compile php, and get a fatal error U1077, cl.exe return with code 0x2.

**Comment by TysonAndre** [comment]
> I try to compile php, and get a fatal error U1077, cl.exe return with code 0x2.

Issues with compiling php or issues with your compiler setup are outside of the scope of igbinary's issue tracker. The instructions for WINDOWS.md haven't been used recently, and may be out of date for whatever php version you're trying to compile. See https://wiki.php.net/internals/windows/stepbystepbuild for newer documentation

**Comment by tomatoweb** [comment]
Use PHP serializer insteed of IGBINARY serializer on Windows systems:

https://github.com/phpredis/phpredis#setoption

$redis->setOption(
   (object)[
	   'instance' 	=> ['127.0.0.1', '6379'],
	   'db'		=> 2,
	   'options' 	=> [
		   \Redis::OPT_PREFIX => 'my_database:',
		   //\Redis::OPT_SERIALIZER => \Redis::SERIALIZER_IGBINARY, // Linux
		   \Redis::OPT_SERIALIZER => \Redis::SERIALIZER_PHP,		   // Windows
		   ]);
