### ISSUE TITLE
Use igbinary with redis session backend, save empty session will cause an error

### ISSUE THREAD

**Issue by vibbow** [igbinary/igbinary#231]
### Summary
When igbinary is enabled as PHP session serialize_handler and using Redis as session backend.
Save an empty session will failed and generated an error.

### System Environment:
OS: Windows 2016
Web server: IIS 10
PHP: 7.2.15 / 7.3.2 (x64 nts)
igbinary ext: 3.0.0a1 (https://pecl.php.net/package/igbinary)
redis ext: 4.2.0 (https://pecl.php.net/package/redis)

### How to reproduce:
1. Clean up all session cookies in browser.
2. Run following PHP scripts:
```
<?php
session_start();
?>
```

### Except behaviour:
A new empty session is saved in redis.

### Actually behaviour:
Session saved failed with following error (this error is write to PHP error log)
> PHP Warning:  Unknown: Failed to write session data (redis). Please verify that the current setting of session.save_path is correct

### Temp work around:
Disable igbinary
or
Write some data to session
or
Use files as session storage backend

**Comment by TysonAndre** [comment]
So, phpredis started rejecting serializing as the empty string in https://github.com/phpredis/phpredis/commit/aaaf0f233afe404bc1d8c6a600af860448ee0bd6#diff-a8c2cac018b55b5883b8faad30efbfb4R661

And igbinary started serializing the empty session as the empty string because of https://github.com/igbinary/igbinary/issues/146

That change to igbinary was implemented in the PR https://github.com/igbinary/igbinary/pull/148

**Comment by TysonAndre** [comment]
It looks like I may have been mistaken, and the other serializers aren't really the empty string. This issue is only seen with igbinary, and not session.serialize_handler=php_serialize (definitely not empty), session.serialize_handler=php_binary, or session.serialize_handler=php

**Comment by TysonAndre** [comment]
There was a misunderstanding in https://github.com/igbinary/igbinary/issues/146 , apparently. Will revert that in the next release (should be backwards compatible), hopefully by tonight 

```php
PS_SERIALIZER_ENCODE_FUNC(php_binary) /* {{{ */
{
	smart_str buf = {0};
	php_serialize_data_t var_hash;
	PS_ENCODE_VARS;

	PHP_VAR_SERIALIZE_INIT(var_hash);

	PS_ENCODE_LOOP(
			if (ZSTR_LEN(key) > PS_BIN_MAX) continue;
			smart_str_appendc(&buf, (unsigned char)ZSTR_LEN(key));
			smart_str_appendl(&buf, ZSTR_VAL(key), ZSTR_LEN(key));
			php_var_serialize(&buf, struc, &var_hash);
		} else {
			if (ZSTR_LEN(key) > PS_BIN_MAX) continue;
			smart_str_appendc(&buf, (unsigned char) (ZSTR_LEN(key) & PS_BIN_UNDEF));
			smart_str_appendl(&buf, ZSTR_VAL(key), ZSTR_LEN(key));
	);

	smart_str_0(&buf);  // This appends a 0 to the end of the string for the 'php_binary' serializer, so it's not really an empty string for $_SESSION == [], it's "\x00"
	PHP_VAR_SERIALIZE_DESTROY(var_hash);

	return buf.s;
}
```
