### ISSUE TITLE
Support php 7.4 __serialize/__unserialize and add new data type

### ISSUE THREAD

**Issue by TysonAndre** [igbinary/igbinary#237]
https://wiki.php.net/rfc/custom_object_serialization

**Comment by nicolas-grekas** [comment]
I just hit this issue today, this means the extension doesn't work with 7.4, e.g.:
```
php > var_dump(igbinary_unserialize(igbinary_serialize(new DateTime)));

PHP Warning:  Uncaught Error: Invalid serialization data for DateTime object in php shell code:1
Stack trace:
#0 [internal function]: DateTime->__wakeup()
#1 php shell code(1): igbinary_unserialize('\x00\x00\x00\x02\x17\x08DateTime\x14...')
#2 {main}
  thrown in php shell code on line 1
```

**Comment by vladrusu** [comment]
Maybe it's just me, but I don't receive any error with **var_dump(igbinary_unserialize(igbinary_serialize(new DateTime)));**

The DateTime object is returned correctly.

Using PHP 7.4 final and igbinary 3.0.1.

**Comment by TysonAndre** [comment]
Like php's serialize(), this is just using the same serialization format as if __serialize wasn't used, and the object had those properties. There are no new data types.

To make switching from/to igbinary to/from serialize()/unserialize() easier, this __serialize()/__unserialize() functionality is only provided in 7.4+
