### ISSUE TITLE
Serialization performance & size comparison

### ISSUE THREAD

**Issue by spajak** [igbinary/igbinary#243]
I was wonder what is the output size and speed for common serializers (including igbinary). So I've made a small comparison:
https://gist.github.com/spajak/d07a999deb0430e2b6b7e58fc44213d1

**Comment by TysonAndre** [comment]
> Unserialization performance is at least on par with the standard PHP serializer, and is much faster for repetitive data. Serialization performance depends on the igbinary.compact_strings option which enables duplicate string tracking. String are inserted to a hash table, which adds some overhead when serializing. In usual scenarios this does not have much of an impact, because the typical usage pattern is "serialize rarely, unserialize often". With the compact_strings option enabled, igbinary is usually a bit slower than the standard serializer. Without it, igbinary is a bit faster.

It doesn't say if compact_strings is used, I assume it's on.

Related to #185

**Comment by spajak** [comment]
Yes it's on. It can be seen by [repeatable] output size, but I will make it clear in the code.
I will also make it a table like view.
If you know other serializers I could add please let me know.
