### ISSUE TITLE
Serialization and unserialization of DateTime is broken in 7.4 

### ISSUE THREAD

**Issue by TysonAndre** [igbinary/igbinary#244]
Due to #237

> I just hit this issue today, this means the extension doesn't work with 7.4, e.g.:
```
php > var_dump(igbinary_unserialize(igbinary_serialize(new DateTime)));

PHP Warning:  Uncaught Error: Invalid serialization data for DateTime object in php shell code:1
Stack trace:
#0 [internal function]: DateTime->__wakeup()
#1 php shell code(1): igbinary_unserialize('\x00\x00\x00\x02\x17\x08DateTime\x14...')
#2 {main}
  thrown in php shell code on line 1
```

_Originally posted by @nicolas-grekas in https://github.com/igbinary/igbinary/issues/237#issuecomment-533572740_

**Comment by TysonAndre** [comment]
Okay, it looks like this might be a different issue from __serialize().

The format of native `serialize()` is the same in php 7.3 and 7.4 (`O:8:"DateTime":3:`, an object with 3 properties).

And I'd want igbinary_serialize to be the same on the same date times in php 7.3 and 7.4, like serialize() is doing. Otherwise, sending data from igbinary in php 7.3 to/from 7.4 wouldn't work.

```php
php > echo serialize(new DateTime());
O:8:"DateTime":3:{s:4:"date";s:26:"2019-09-20 14:22:03.192497";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}
```

**Comment by TysonAndre** [comment]
Oh. never mind.

PHP `serialize()` went with the exact same serialization format with/without `__serialize()`. I didn't expect that (code would behave differently in php 7.3 and 7.4)

```
php > class Foo { public function __serialize() { return ['abc' => 'fed']; }}
php > echo serialize(new Foo());
O:3:"Foo":1:{s:3:"abc";s:3:"fed";}
php > class Foe { public $abc = 'fed'; }
php > echo serialize(new Foe());
O:3:"Foe":1:{s:3:"abc";s:3:"fed";}
```

**Comment by vladrusu** [comment]
Maybe it's just me, but I don't receive any error with var_dump(igbinary_unserialize(igbinary_serialize(new DateTime)));

The DateTime object is returned correctly.

Using PHP 7.4 final and igbinary 3.0.1.
