### ISSUE TITLE
igbinary and php 7.4 install

### ISSUE THREAD

**Issue by hotdog666** [igbinary/igbinary#246]
hi, i use php 7.4 and get this warning
`PHP Warning:  PHP Startup: Unable to load dynamic library 'igbinary' (tried: /usr/lib/php/20190902/igbinary (/usr/lib/php/20190902/igbinary: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/igbinary.so (/usr/lib/php/20190902/igbinary.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

igbinary installed to 20180731
how fix it?

**Comment by TysonAndre** [comment]
See #237 and #244 - Igbinary doesn't support php 7.4 yet, which is probably why it isn't provided by the package maintainer.

https://www.php.net/manual/en/migration74.new-features.php#migration74.new-features.standard.magic-serialize has a lot more work to implement and to verify that there aren't memory leaks or bugs.

**Comment by TysonAndre** [comment]
igbinary 3.1.0b1 should support __serialize/__unserialize, but php 7.4's typed properties may cause various edge cases in error handling/reference counting/__destruct that aren't supported yet. (e.g. adding/changing typed properties types in the php class declaration to something incompatible with the serialized data)

It should work for code that doesn't use typed properties, though

**Comment by TysonAndre** [comment]
#205 tracks the crashes in unserialization when typed properties are used.

**Comment by TysonAndre** [comment]
igbinary 3.1.0b2 should be used instead
