### ISSUE TITLE
Look into alternative hash implementations for hash_si_*

### ISSUE THREAD

**Issue by TysonAndre** [igbinary/igbinary#262]
e.g. cuckoo hashing, different probing strategies, etc.

Check if they improve serialization performance when there are a lot of unique strings, or heavy reuse of a few strings.

The current probing strategy and fill factor seemed to work well, but there may be improvements.

**Comment by phadej** [comment]
One important insight is that the hash structure is short-lived, and we don't need to remove things from it. I vaguely remember that some corners are cut there at least using the latest. That's allows using simple (i.e. fast) linear probing.

I also don't remember if 3/4 fill rate was found experimentally, looks like it's already there in the initial commit. So probably isn't.

```c
hash_si_init(&igsd->strings, 16); // we could also start with a bit bigger initial hash table, machines have grown in the last decade
```
