### ISSUE TITLE
Values of copied array sometimes serializing as references under PHP 7.3

### ISSUE THREAD

**Issue by ralfstrobel** [igbinary/igbinary#268]
We encountered this very strange behavior that seems to occur only in combination with PHP 7.3 (currently 7.3.14) but not 7.2. We were able to reproduce it with both igbinary 3.1.2 and 3.0.1.

EDIT: This is the revised synthetic reproduction (see post history for first attempt).
```
//Data must be an array of at least depth 2
$data = [['hello', 'world']];
//Each leaf value must have been accessed
array_walk_recursive($data, function ($value) {});

//Then a second array must be constructed element-wise from the first
$data2 = [$data[0]];

//Then both arrays need to be serialized together
$a = [$data, $data2];
$b = igbinary_unserialize(igbinary_serialize($a));

print serialize($a) . "\n";
print serialize($b) . "\n"; 
```
Note that no explicit references are ever used during the code.

Output of the first serialize() is as expected for PHPs copy-on-write mechanism:
`a:2:{i:0;a:1:{i:0;a:2:{i:0;s:5:"hello";i:1;s:5:"world";}}i:1;a:1:{i:0;a:2:{i:0;s:5:"hello";i:1;s:5:"world";}}}`
Output for the second serialize after igbinary-serialization is:
`a:2:{i:0;a:1:{i:0;a:2:{i:0;s:5:"hello";i:1;s:5:"world";}}i:1;a:1:{i:0;a:2:{i:0;R:4;i:1;R:5;}}}`

Each leaf value of $data2 is suddenly a reference to the corresponding value in $data. Naturally this can be the cause of major unintended program behavior.

**Comment by TysonAndre** [comment]
Possibly related to https://github.com/igbinary/igbinary/issues/214#issuecomment-432877391

This is just a guess; I haven't tried reproducing this yet, and don't remember if this is how it was implemented. It might be related to $this->data becoming part of one reference group, and $this->originalData becoming part of an unrelated reference group (i.e. `$a = &$this->data`, and `$b = &$this->originalData`), and php 7.3 possibly being less aggressive about cleaning up reference groups when there's only one reference. (e.g. for cyclic data structures containing references)

If they're actually private, I don't know what would cause your issue to happen, unless there's a library which is using reflection to access it.

> Aside (For future reference): It seems like serialize() takes a different approach to references than igbinary_serialize() - The first time it sees a value (not a key), it tracks that value as something that could become a reference. The second time, it emits a reference to the index of that value (R:2). So, I think it's able to make any value a reference retroactively
>
> Unfortunately, I can't really change the way references are represented (i.e. using 0x25 for the first reference to a value) in version 2 (0x00000002) of igbinary, as older installations would be unable to unserialize data)

**Comment by ralfstrobel** [comment]
Thank you for your quick reply! Your comment lead me onto the correct path. It was indeed not the private data copy inside of the object that caused the issue, but an array_walk_recursive that occurred before the constructor was even called - in conjunction with an element-wise normalization inside of the class.

I have rewritten my original post with a short synthetic reproduction now. Hope this helps!

**Comment by TysonAndre** [comment]
```php
//Data must be an array of at least depth 2
$data = [['hello', 'world']];
//Each leaf value must have been accessed
array_walk_recursive($data, function ($value) {});

//Then a second array must be constructed element-wise from the first
$data2 = [$data[0]];

//Then both arrays need to be serialized together
$a = [$data, $data2];
$b = igbinary_unserialize(igbinary_serialize($a));
debug_zval_dump($b);
$b[0][0][0] = 'HELLO';
debug_zval_dump($b);
/*
array(2) refcount(2){
  [0]=>
  array(1) refcount(1){
    [0]=>
    array(2) refcount(1){
      [0]=>
      &string(5) "HELLO" refcount(2)
      [1]=>
      &string(5) "world" refcount(1)
    }
  }
  [1]=>
  array(1) refcount(1){
    [0]=>
    array(2) refcount(1){
      [0]=>
      &string(5) "HELLO" refcount(2)
      [1]=>
      &string(5) "world" refcount(1)
    }
  }
}
*/
```

I can also confirm this modifies both arrays, so this bug does have an impact (`$b[1][0][0]` also becomes HELLO - doing the same to $a would not affect the second copy). I thought the reference group of size 1 might get ignored, but was mistaken.

**Comment by TysonAndre** [comment]
Other notes:

- This does not fix the general case, e.g. if a value is part of a reference group that isn't serialized.

   Maybe the unserializer should be what dereferences reference groups of size 1.
- Still not sure why the value created in userland doesn't get modified, but the value igbinary creates does. I'll want to look into that.
- Will need to check if #269 is safe with reference cycles; it probably is.
- Can array_walk be sped up in php itself by avoiding creating those references if the callable doesn't expect varargs/references for the first arg? (low priority)

**Comment by ralfstrobel** [comment]
Thank you for the fix.

> Still not sure why the value created in userland doesn't get modified, but the value igbinary creates does. I'll want to look into that.
From my perspective the userland behavior is correct. Since none of the code ever assigns anything by reference, the values should effectively behave like separate copies. They may internally correspond to the same zval, but are subject to the copy-on-write mechanism.

Though it is actually a valid criticism that PHPs own serialization function is not capable of representing such a pending copy-on-write state but will represent them as actual redundant values. I don't know if igbinary is better in this regard, but if not it could be an optimization route worth investigating.

**Comment by ralfstrobel** [comment]
I've been doing some more research on the underlying issue in the context of performance optimization, including some reading up on the C implementation of PHP 7, which I now understand a lot better...

> php 7.3 possibly being less aggressive about cleaning up reference groups when there's only one reference. (e.g. for cyclic data structures containing references)

This is something I am still curious about. @TysonAndre have you by any chance encountered an explanation for the change in the treatment of reference groups? Currently testing with PHP 7.4, it is definitely very easy to create leftover IS_REFERENCE zvals inside nested arrays.

Our application works with semi-structured data in the form of arrays a lot, so I checked a few sample locations using xdebug_debug_zval(), and it looks like large part of our data trees very quickly devolve into having all of their inner nodes and leaves of type IS_REFERENCE - be it because some code used array_walk() or because some sub-tree was passed by reference.

I can't imagine that's very great for performance, though I have not done any benchmarks on it yet. Is this an issue that is being discussed in the PHP developer community? I am not very tied-in with them, but at first glance I could not find much about it.

> Maybe the unserializer should be what dereferences reference groups of size 1

In retrospective I am honestly quite glad you fixed the issue in the serializer. This way our devolved data trees are already sanitized  before we serialize and cache them, which probably leads to smaller cache content and less effort when they are unserialized.

**Comment by TysonAndre** [comment]
> have you by any chance encountered an explanation for the change in the treatment of reference groups? Currently testing with PHP 7.4, it is definitely very easy to create leftover IS_REFERENCE zvals inside nested arrays.

It's probably due to fixes for handling of references, likely  https://github.com/php/php-src/commit/61d00a6cf3d5e8471cc05bdb686b1f399c0f15a4 (not definitely) 

> Use COPY_DEREF instead of COPY_UNREF
> 
> This fixes the behavior when the storage location of the fetch is
> modified before the operand is dereferenced by the using VM opcode.
> 
> Furthermore it elimiates references as a possible return value from
> *_R opcodes, which will give us more opportunities for inferences,
> in particular in regard to typed properties.


I initially thought it might have been a bug fix for GLOBALS or circular reference loops, but was probably mistaken.

> I can't imagine that's very great for performance, though I have not done any benchmarks on it yet. Is this an issue that is being discussed in the PHP developer community? I am not very tied-in with them, but at first glance I could not find much about it.

If it suits your application, you may want to write an alternative to array_walk as an ordinary php function. https://php.net/array_walk always converts values to references, which have their own overhead. In addition to that, there's overhead in switching from C to the php vm for each time the closure is called from php (for setting up the php vm again, etc.)

**Comment by ralfstrobel** [comment]
Indeed, the following replacement seems to perform about 15% better in terms of both run time and memory usage. It also does not leave behind inner reference zvals in the array, as the re-assignment into the array seems to deref the value.

```
function arrayWalkRecursive(array &$array, callable $callback): void
{
    foreach ($array as $key => $value) {
        $array[$key] = null;
        try {
            if (is_array($value)) {
                arrayWalkRecursive($value, $callback);
            } else {
                $callback($value);
            }
        } finally {
            $array[$key] = $value;
        }
    }
}
```

Since passing each value to the callback by rererence is a common use case, I think it is fine that the native functions are geared towards this (not that I would mind optimization when it is unnecessary). Mostly I still think in this case the C code should check whether the refcount is back to 1 upon return from the userland function and if so unpack the original zval.

Honestly, maybe this should even be anchored deeper into userland function calls and by-reference iterations, otherwise the zval landscape is just bound to become more and more cluttered with references through normal use. But at this point we certainly have left the scope of my knowledge on PHP internals. Maybe once I have verified the situation is still the same in PHP 8.x I'll ask about it in the PHP internals mailing list or some other place.
