### ISSUE TITLE
Failed test against 7.4.6RC1

### ISSUE THREAD

**Issue by remicollet** [igbinary/igbinary#274]
Hi,

Discovered in Fedora CI:
https://koschei.fedoraproject.org/package/php-pecl-igbinary?collection=f33

Since 7.4.6RC1 1 test start failing
```
TEST 12/112 [tests/__serialize_012.phpt]
========DIFF========
003+   object(__PHP_Incomplete_Class)#3 (5) {
003-   object(__PHP_Incomplete_Class)#3 (4) {
014+     ["3"]=>
015+     NULL
========DONE========
FAIL Test unserialization of classes derived from ArrayIterator [tests/__serialize_012.phpt] 

```

**Comment by remicollet** [comment]
Seems related to http://git.php.net/?p=php-src.git;a=commitdiff;h=0d11d373574a7f831db6e3a7add60f2bbe28413f

(see changes to ext/standard/tests/serialize/bug45706.phpt)

**Comment by TysonAndre** [comment]
Thanks, this should probably also add a test of whatever changed in ArrayObject.

I'll have to look into how to support both 7.4.5 and 7.4.6.
