### ISSUE TITLE
Fix or update tests for remaining php 8.0 failures on nightly builds

### ISSUE THREAD

**Issue by TysonAndre** [igbinary/igbinary#278]
e.g. add a different test if the rendering of cyclic values is slightly different in php 8.0

**Comment by heddn** [comment]
I this what is causing my compile failures in https://git.mtech-llc.com/open-source/drupal-docker/-/jobs/5770#L708

**Comment by andypost** [comment]
@heddn it looks separate API change

**Comment by TysonAndre** [comment]
That looks like an issue in phpredis at a glance. Also, I haven't checked, but you want the master branch of igbinary - the php8 compatibility fixes for the latest commits to php 8.0 aren't in a pecl release yet.

**Comment by andypost** [comment]
Same for php redis - it needs to use master https://github.com/phpredis/phpredis/commit/a7662da7924dcbaa74f5f2c6e1dce06b19e64bfc

**Comment by heddn** [comment]
I'm using the latest for redis. I'll see about doing the same for igbinary as well. Thanks.

**Comment by TysonAndre** [comment]
It seems like the issue @heddn  reported was fixed in https://github.com/phpredis/phpredis/commit/a7662da7924dcbaa74f5f2c6e1dce06b19e64bfc

**Comment by TysonAndre** [comment]
```
Check for reference serialization (Original example, not using var_dump) [tests/igbinary_009b.phpt]
Cyclic array test [tests/igbinary_026.phpt]
Cyclic array test 2 [tests/igbinary_026b.phpt]
```

These all seem harmless, and the only thing that changed was the var_dump output for cyclic reference arrays after unserialization (and possibly before, unrelated to igbinary)

**Comment by andypost** [comment]
Yes, this tests probably needs split for 8.x

**Comment by TysonAndre** [comment]
> Yes, this tests probably needs split for 8.x

I was planning on that if that was only a change in the representation emitted by var_dump (or handling of cyclic arrays when passed to functions by php)
