### ISSUE TITLE
Unserialization of an ArrayObject reference which was created outside of the class causes an Error 503

### ISSUE THREAD

**Issue by Shebbyy** [igbinary/igbinary#281]
Igbinary Version: 3.1.3
PHP-Version: 7.4.8

If you create an ArrayObject, or any SubClass of it and end up setting it into a class as a reference, unserializing that class would in turn cause Apache to die with the error 503 Service not available!
Apache FPM Error Log:
[29-Jul-2020 15:23:55] WARNING: [pool URL] child 29644 exited on signal 11 (SIGSEGV - core dumped) after 55.984663 seconds from start
[29-Jul-2020 15:23:55] NOTICE: [pool URL] child 30246 started

This is a short example to recreate the error:

```
class TestClass {
  private $env;
  public function setEnv(ArrayObject &$e) {
    $this->env = &$e;
  }
}

$arrayObject = new ArrayObject();

$testClass = new TestClass();
$testClass->setEnv($arrayObject);

igbinary_unserialize(igbinary_serialize($testClass));
```

In the 3.1.2 release of igbinary this code also caused the same behavior, now since 3.1.3 though it works without any issues:
```
class MyClass {

  private $arrayObjectMember;

  public function __construct() {
    $arrayObject = new ArrayObject();
    $this->arrayObjectMember = &$arrayObject;
  }
}

$myClassInstance = new MyClass();
igbinary_unserialize(igbinary_serialize($myClassInstance));
```

**Comment by TysonAndre** [comment]
Probably related to `__serialize` in php 7.4. Potentially also related to changes in php to support typed properties, which should also be tested.

**Comment by sschuerz** [comment]
Interestingly, the problem does not occur if the passed `ArrayObject` instance is not assigned to a variable for passing it to the object getting serialized - i.e. this code works:
```
class TestClass {
  private $env;
  public function setEnv(ArrayObject &$e) {
    $this->env = &$e;
  }
}

$testClass = new TestClass();
$testClass->setEnv(new ArrayObject());

igbinary_unserialize(igbinary_serialize($testClass));
```

**Comment by TysonAndre** [comment]
> Interestingly, the problem does not occur if the passed ArrayObject instance is not assigned to a variable for passing it to the object getting serialized - i.e. this code works:

If a reference group is of size 1, then php can safely/transparently convert it back into a non-reference
