### ISSUE TITLE
Data corruption when serializing object containing objects and with `var_dump()`/`print_r()`

### ISSUE THREAD

**Issue by Kocal** [igbinary/igbinary#287]
Hi!

Today I faced an issue when upgrading from PHP 7.3 to 7.4 on a project which use `igbinary`.

When using `var_dump()` or `print_r()`, I'm having an issue with objects instances that can be the same where they should/can not be the same.

I've opened an issue on Symfony repository (https://github.com/symfony/symfony/issues/38440) but @nicolas-grekas confirms that's related to igbinary and not Symfony, see https://github.com/Kocal/symfony-marshaller-or-cache-issue/pull/1. 
@Nyholm provided some dummy classes which also reproduce the issue, see https://github.com/symfony/symfony/issues/38440#issuecomment-704383897, this way we can exclude the Symfony Mailer/Mime classes from being part of the issue.

## How to reproduce

1. clone https://github.com/Kocal/symfony-marshaller-or-cache-issue
2. use PHP 7.4 with igbinary 3.1.5
3. run `php reproducer.php`, notice the last `bool(true)` when `var_dump($messageEvents)` **is not commented**:
![2020-10-06_20-21](https://user-images.githubusercontent.com/2103975/95244080-cce5a380-0811-11eb-80d0-de45b5076cf3.png)
4. comment `var_dump($messageEvents)` from line 14
5. run `php reproducer.php`, notice the last `bool(false)` when `var_dump($messageEvents)` **is commented**:
![2020-10-06_20-22](https://user-images.githubusercontent.com/2103975/95244076-cc4d0d00-0811-11eb-9899-049c7430d9a3.png)

I expect the code `$messageEvents->getEvents()[0]->getMessage()->getHeaders() === $messageEvents->getEvents()[1]->getMessage()->getHeaders()` to equals `false`, since `$messageEvents->getEvents()[0]->getMessage()` and `$messageEvents->getEvents()[1]->getMessage()` are different [`Email`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mime/Email.php) instances, and  new [`Headers`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mime/Header/Headers.php) instances are created when creating an `Email`.

In the first place, without thinking about the reproducer, I saw the issue on my library [SymfonyMailerTesting](https://github.com/Kocal/SymfonyMailerTesting) when trying to normalize an `Email` instance (comming from the Symfony Cache, which use the [`DefaultMarshaller`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/Marshaller/DefaultMarshaller.php) which use igbinary). I don't use `var_dump()` or `print_r()`, but traversing `Email`'s properties to normalize it... so maybe the issue is related to object properties traversing?

Do you know what can happens here?
Thanks!

**Comment by Kocal** [comment]
Test added in #288 but it does not fail as expected.
I was not able to reproduce using dummy classes `Outer`/`Inner` so I tried to recreate Symfony Mime/Mailer classes (`MessageEvents`, `MessageEvent`, `Message`, `Email`, etc...) and test them but it still does not fail... :shrug:

**Comment by Nyholm** [comment]
My outer/inner could not reproduce the issue. 

Did you see this change to the reproducer? https://github.com/Kocal/symfony-marshaller-or-cache-issue/pull/1

Also, I needed to turn off xdebug to be able to reproduce the issue.

**Comment by TysonAndre** [comment]
What patch version of php 7.4 are you using? The latest is https://www.php.net/downloads.php#v7.4.11 - there may have been changes to serialization since then. Does it happen even when opcache is disabled? What's the output of `php -m`

**Comment by TysonAndre** [comment]
> I'm using PHP 7.4.10 with igbinary 3.1.5.

Oh, saw that in the symfony issue

**Comment by TysonAndre** [comment]
```
    /**
     * @internal
     */
    public function __serialize(): array
    {
        if (\is_resource($this->text)) {
            $this->text = (new TextPart($this->text))->getBody();
        }

        if (\is_resource($this->html)) {
            $this->html = (new TextPart($this->html))->getBody();
        }

        foreach ($this->attachments as $i => $attachment) {
            if (isset($attachment['body']) && \is_resource($attachment['body'])) {
                $this->attachments[$i]['body'] = (new TextPart($attachment['body']))->getBody();
            }
        }

        return [$this->text, $this->textCharset, $this->html, $this->htmlCharset, $this->attachments, parent::__serialize()];
    }
```

I see that it does use `__serialize` and `__unserialize` in some places such as vendor/symfony/mime/Email.php - you may need to include that in a reproducer

**Comment by Kocal** [comment]
Do you think I can setup composer and directly require Symfony classes in this test, or do you prefer we keep trying to re-create Symfony classes here?

**Comment by Kocal** [comment]
Okay great, I literally copy/pasted some Symfony classes which were needed for the reproducer and... it reproduce the issue! :tada:

**Comment by TysonAndre** [comment]
Do you see any other issues in php 7.4 if you compile and install #289 ?

I was planning to publish a release candidate this week with that PR if no other issues were discovered

**Comment by Kocal** [comment]
No I don't see any issues, everything is working (`make test` and `php reproducer.php`).
A big thank you! :)
