### ISSUE TITLE
Segfault with igbinary_unserialize() php7 if assigned reference to object property

### ISSUE THREAD

**Issue by jzemlo** [igbinary/igbinary#299]
test.php
```
<?php
class ClassA
{
    public $field;

    public function __construct()
    {
        $this->field = new ArrayObject([12]);
//        $xRef = &$this->field;
    }
}


$x = new ClassA();
$xRef = &$x->field;

$y = igbinary_serialize($x);
$z = igbinary_unserialize($y);
print_r($z);
```

```
$ php test.php
Segmentation fault (core dumped)
```

I use standard ubuntu 20.04 LTS setup
```
$ php -v
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

$ php -i | grep igbi
/etc/php/7.4/cli/conf.d/20-igbinary.ini,
apc.serializer => igbinary => igbinary
igbinary
igbinary support => enabled
igbinary version => 3.1.2
igbinary APCu serializer ABI => 0
igbinary session support => yes
igbinary.compact_strings => On => On
Registered serializer handlers => php_serialize php php_binary igbinary
```

**Comment by TysonAndre** [comment]
At the time of writing - the latest release of igbinary is 3.1.6, and your example is using 3.1.2 https://github.com/igbinary/igbinary/releases

Ubuntu doesn't seem to be providing anything newer than 3.1.2 - an issue should be filed in their issue tracker. Notably, 3.1.3 fixes this issue - Properly serialize reference groups of size 1 (these can be created by array_walk_recursive and other functions).

Probably a duplicate of https://github.com/igbinary/igbinary/issues/268

**Comment by TysonAndre** [comment]
A similar issue from the ubuntu bug tracker for an older ubuntu version is https://bugs.launchpad.net/ubuntu/+source/php-igbinary/+bug/1651031

I'd recommend installing the latest version through pecl, enabling it in php.ini, and uninstalling the `php-igbinary` version packaged by ubuntu, until it's fixed

**Comment by TysonAndre** [comment]
I've also seen https://launchpad.net/~ondrej/+archive/ubuntu/php suggested elsewhere for more frequent updates
