### ISSUE TITLE
Docker PHP 7.4 alpine build (php:7.4-cli-alpine) fails src/php7/igbinary.lo Error 127 (/bin/sh: Operation not permitted)

### ISSUE THREAD

**Issue by Patrick-Remy** [igbinary/igbinary#333]
When try to installing igbinary via `pecl` on php 7.4 alpine image, make fails. Seems that at least >=3.0 versions are affected on my quick tests.

How to Reproduce:
```sh
docker run --rm -it php:7.4-cli-alpine sh
/ # apk add --no-cache autoconf automake make libtool gcc libgcc g++ libstdc++
....
/ #  pecl install igbinary
```

Error log:
```
....
creating libtool
appending configuration tag "CXX" to libtool
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/sh /tmp/pear/temp/pear-build-defaultusermaOBja/igbinary-3.2.3/libtool --mode=compile cc -g -O2 -O2 -Wall -Wpointer-arith -Wcast-align -Wwrite-strings -Wswitch -finline-limit=10000 --param large-function-growth=10000 --param inline-unit-growth=10000 -I. -I/tmp/pear/temp/igbinary -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultusermaOBja/igbinary-3.2.3/include -I/tmp/pear/temp/pear-build-defaultusermaOBja/igbinary-3.2.3/main -I/tmp/pear/temp/igbinary -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/igbinary/src/php7/igbinary.c -o src/php7/igbinary.lo
make: /bin/sh: Operation not permitted
make: *** [Makefile:192: src/php7/igbinary.lo] Error 127
ERROR: `make' failed
```

**Comment by TysonAndre** [comment]
1. Does the igbinary dependency already exist?
2. Why not use the php 7.4 igbinary package from apk instead?
3. Are you sure you're consistently using packages from the same alpine base image? https://gitlab.alpinelinux.org/alpine/aports/-/issues/12396 suggests this may happen when mixing packages from different alpine releases

   https://github.com/docker-library/php/issues/1130
4. Are you sure you're running this with the right user (e.g. permitted to create files)
5. Did you pull the latest 7.4-cli-alpine?

"Operation not permitted" seems less like a compilation issue than an OS (alpine or permissions) issue

**Comment by TysonAndre** [comment]
@Patrick-Remy https://github.com/alpinelinux/docker-alpine/issues/146#issuecomment-869595012 seems related

> for those who faced with this issue on Alpine 3.14:
>
> please check https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2 and ensure that your docker is 20.10.0 or higher.

**Comment by Patrick-Remy** [comment]
Thanks for your fast reply! I can confirm your assumption that it is related to the docker version, on 18.09 the problem occurs on at least 20.10.7 it is fixed. So it seems to be related to the alpine changes.

For completeness:
- igbinary dependency did not exist before in the image, raw build steps above, and it did working for years
- i am using consistent packages 
- i am sure it is running with the correct user rights
- it is the latest 7.4-cli-alpine image
