### ISSUE TITLE
Serialize + Unserialize of array puts array pointer beyond end of array (on PHP <= 7.2)

### ISSUE THREAD

**Issue by toubsen** [igbinary/igbinary#338]
**Describe the bug**
Serializing + unserializing a nested array with igbinary will result in a different pointer structure in the unserialized array, that breaks e.g. the `current()` function.

Broken version: `SNAPSHOT build @fc46c4ebf5fa4793e346e933683b2a2e7e2eae8b`
Previous non-broken version: `SNAPSHOT build @4f49930f42d66d6884e20f13954ff9bfdcbf6440`

Used the builds produced by @oerdnj
https://github.com/oerdnj/deb.sury.org/

Related issue (closed + redirected to upstream):
https://github.com/oerdnj/deb.sury.org/issues/1626

**To Reproduce**
1. Run minimal reproducer PHP script (e.g. from CLI)

```
$arr = [
	'one' => [
		'two' => [
			'three' => [
				'four'
			],
		],
	],
];
$test = current(current(current(current($arr))));

echo $test . "\n";

$arr2 = igbinary_unserialize(igbinary_serialize($arr));
$test2 = current(current(current(current($arr2))));

echo $test2 . "\n";
```

**Expected behavior**
Original and serialized + unserialized array should behave the same

Expected output from reproducer:
```
four
four
```

Actual output from reproducer:
```
four
PHP Warning:  current() expects parameter 1 to be array, boolean given in foo.php on line 16

Warning: current() expects parameter 1 to be array, boolean given in foo.php on line 16
PHP Warning:  current() expects parameter 1 to be array, null given in foo.php on line 16

Warning: current() expects parameter 1 to be array, null given in foo.php on line 16
PHP Warning:  current() expects parameter 1 to be array, null given in foo.php on line 16

Warning: current() expects parameter 1 to be array, null given in foo.php on line 16
```

**Distribution (please complete the following information):**
 - OS: Debian GNU/Linux 9.13 (stretch)
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s):**
```
php7.2-igbinary:
  Installed: 3.2.4+2.0.8-1+0~20210802.26+debian9~1.gbpfc46c4
```

**Additional context**
The PHP 8 version of the package with the same git / build version is not broken:
`php8.0-igbinary: 3.2.4+2.0.8-1+0~20210802.26+debian9~1.gbpfc46c4`

**Comment by TysonAndre** [comment]
I can reproduce this in php 7.2 but not 7.3, 7.4, or 8.0
