### ISSUE TITLE
Version mismatch between package.xml/source

### ISSUE THREAD

**Issue by pagelypete** [igbinary/igbinary#342]
It looks like although `package.yml` defines the current version as `3.2.5`, the source doesn't - https://github.com/igbinary/igbinary/blob/master/src/php7/igbinary.h#L21

If you try and install `igbinary` right now with `pickle` then you will get a fatal due to this unless you use `--version-override 3.2.5`

**Comment by TysonAndre** [comment]
Fixed in 3.2.6
