### ISSUE TITLE
PHP 8.1 Windows DLLs missing - pecl.php.net

### ISSUE THREAD

**Issue by mlhkr** [igbinary/igbinary#352]
PHP 8.1 Windows DLLs missing - pecl.php.net

**Comment by TysonAndre** [comment]
I think it'll be in https://windows.php.net/downloads/pecl/snaps/igbinary/ for 3.2.7 when the 3.2.7 release is published, though I may have to contact the windows for php team if it isn't automatic. See https://windows.php.net/

See #353 

> A week ago PHP 8.1.0 has been released and you may be eager to try it out, but you need one or more PECL packages for which there are no PHP 8.1 binary packages available yet, and you may wonder when these will be made available. Well, the PHP for Windows team does not want to provide possibly premature binary packages, **so as usual, we will wait until late January or early February to trigger the mass build for all applicable PECL packages; that is, after PHP 8.1.2 has been released, what is currently scheduled for January, 20th. After the builds have been done, you can download the binary packages from pecl.php.net as usual.**

> Waiting for two months is no option for you? In that case you can download [snapshot builds](https://windows.php.net/downloads/pecl/snaps/) of some of the PECL packages. If there is no snapshot for your package available, consider to contact the team and to request that a snapshot for that package is being build. Note though, that these snapshot builds are not recommended for production. However, testing these and reporting issues is very welcome!

**Comment by TysonAndre** [comment]
https://pecl.php.net/package/igbinary/3.2.7/windows https://windows.php.net/downloads/pecl/releases/igbinary/3.2.7/ they seem to exist now
