### ISSUE TITLE
`igbinary.so` has size of about 5 MB on linux with gcc

### ISSUE THREAD

**Issue by mvorisek** [igbinary/igbinary#357]
### Expected behaviour

size less than 1 MB

### Actual behaviour

The igbinary ext is very large, much larger than complex extensions like `xdebug` or other data exts.

I belive the size should be investigated, maybe some inline modifiers are overused, or is some heavy lib staticaly compiled in?

**Comment by TysonAndre** [comment]
```diff
--- a/config.m4
+++ b/config.m4
@@ -61,7 +61,7 @@ if test "$PHP_IGBINARY" != "no"; then
   elif test "$GCC" = yes; then
     AC_MSG_RESULT(gcc)
     if test -z "`echo $CFLAGS | grep -- '-O[0123]'`"; then
-      PHP_IGBINARY_CFLAGS="$CFLAGS -O2 -Wall -Wpointer-arith -Wcast-align -Wwrite-strings -Wswitch -finline-limit=10000 --param large-function-growth=10000 --param inline-unit-growth=10000"
+      PHP_IGBINARY_CFLAGS="$CFLAGS -O2 -Wall -Wpointer-arith -Wcast-align -Wwrite-strings -Wswitch"
     fi
```

It's much smaller if you manually remove those flags from config.m4. I'd noticed, but hadn't touched this since I didn't know why the original maintainers added those flags and assumed there might have been a reason (2.4 MB -> 0.059 MB)

**Comment by TysonAndre** [comment]
> Might be worth mentioning that a Windows build doesn't have the same kind of footprint (custom built one I have locally is 68 KB).

`elif test "$GCC" = yes` - it's specific to the gcc compiler.

----

I think it's larger than needed, but most of the 5MB may be debugging symbols.

It's worth checking the generated Makefile to see `CFLAGS` - if `export CFLAGS='-O3'` isn't run before, it inherits the CFLAGS used to build whatever php version was used, and `-g` is added (and debugging symbols add another 500KB).

```sh
export CFLAGS=-O3
phpize
./configure
make clean test install
# 74736 bytes, vs 594896 bytes for "-O3 -g"
```

Alternately https://linux.die.net/man/1/strip can remove debugging symbols
