### ISSUE TITLE
There are a lot of files included in the PECL zip download. Could you explain how to install/where those go on Windows?

### ISSUE THREAD

**Issue by OkilyDokily** [igbinary/igbinary#368]
For example in addition to the dll file there is also igbinary.php file and several other files not even mentioned in the Readme.md docs.

**Comment by TysonAndre** [comment]
You only need php_igbinary.dll from the zip file. In the unlikely event you need to debug igbinary in a debugger, php_igbinary.pdb is there to add debugging symbols for your debugger.

The following files are all license files, and are added to Windows PECL downloads by the PHP for windows team.

- COPYING
- CREDITS

The following files are documentation files, and added to Windows PECL downloads by the PHP for windows team (igbinary's documentation is easy to browse online on github, other PECLs might be hosting on something that's less convenient to browse).

- NEWS
- igbinary.php (igbinary's API documentation stub)
- igbinary.php.ini (example of how to configure it)
- README.md
- TECH_NOTES.md

These are miscellaneous scripts. I don't know why they're included by the windows for PHP team

- igbinary.spec (old file, example for building an rpm for linux. Not sure why that's included.)
- tags.sh (generate ctags files for editors)
