### ISSUE TITLE
Significant drop in performance of igbinary_unserialize() since 3.2.11 related to typed properties

### ISSUE THREAD

**Issue by c-locksmith** [igbinary/igbinary#371]
We have noticed a significant performance drop of igbinary_unserialize() when we upgraded from 3.2.9 to 3.2.12. It turned out that the issue was introduced with version 3.2.11 and specifically seems to be connected to the fixes to typed properties in Issue #363, as mentioned in the [change log](https://pecl.php.net/package-info.php?package=igbinary&version=3.2.11).

This is especially noticeable in our application, which serializes sets of complex PHP objects (using typed properties almost exclusively) into a cache, that is accessed during each request. We registered an increase in run time of igbinary_unserialize() of roughly 100%, which significantly impacted the performance of each request. The issue is at a similar level reproducible with this PHP script creating and serializing a bunch of trivial objects with an attribute that is either typed or untyped:

```
$runs = 1000;

// run test with untyped property

class TestUntypedProperty {
    public $str = 'x';
}

$arr = [];
for ($i = 0; $i < 10000; $i++) {
    $arr[] = new TestUntypedProperty();
}
$serializedUntyped = igbinary_serialize($arr);

$start = microtime(true);
for ($i = 0; $i < $runs; $i++) {
    igbinary_unserialize($serializedUntyped);
}
$end = microtime(true);
echo sprintf("avg unserialize with untyped attribute: %.10f\n", ($end - $start) / $runs);


// run test with typed property

class TestTypedProperty {
    public string $str = 'x';
}

$arr = [];
for ($i = 0; $i < 10000; $i++) {
    $arr[] = new TestTypedProperty();
}
$serializedTyped = igbinary_serialize($arr);

$start = microtime(true);
for ($i = 0; $i < $runs; $i++) {
    igbinary_unserialize($serializedTyped);
}
$end = microtime(true);
echo sprintf("avg unserialize with typed attribute:   %.10f\n", ($end - $start)/$runs);
```

While with igbinary version 3.2.9 the difference between the two test runs is hardly measurable, with version 3.2.12 the avg run time increases by a factor of 1.7x to 2x.

**Comment by TysonAndre** [comment]
> We have noticed a significant performance drop of igbinary_unserialize() when we upgraded from 3.2.9 to 3.2.12. It turned out that the issue was introduced with version 3.2.11 and specifically seems to be connected to the fixes to typed properties in Issue https://github.com/igbinary/igbinary/issues/363, as mentioned in the [change log](https://pecl.php.net/package-info.php?package=igbinary&version=3.2.11).

> This is especially noticeable in our application, which serializes sets of complex PHP objects (using typed properties almost exclusively) into a cache, that is accessed during each request. We registered an increase in run time of igbinary_unserialize() of roughly 100%, which significantly impacted the performance of each request. The issue is at a similar level reproducible with this PHP script creating and serializing a bunch of trivial objects with an attribute that is either typed or untyped:

The absolute cost in performance seems to be the same as you'd see for php's serialize()/unserialize() without igbinary

It's doing more CPU work now that it's reading the typed property info and checking it when assigning. Previously, it was using a faster but wrong helper that didn't check property types, which had the linked bug that it could assign types that shouldn't be possible

A large part of this seems to be due to an instance of https://github.com/php/php-src/issues/9813 - the overhead is smaller if I shift the pointers used. In practice, they're aligned to ZEND_MM_ALIGN and not any larger due to how the allocator works for zend_objects and their property slots

```
# php 8.2.0, with igbinary_unserialize()
avg unserialize with untyped attribute: 0.0008890989
avg unserialize with typed attribute:   0.0021066411
# php 8.2.0, with unserialize()
avg unserialize with untyped attribute: 0.0019850340
avg unserialize with typed attribute:   0.0035299640
```

After the patch, with igbinary_unserialize()
```
avg unserialize with untyped attribute: 0.0009524131
4586328
avg unserialize with typed attribute:   0.0012830188
4586328
```

(Same example, with class names of the same length to compare unserialize())

```php
<?
php
$runs = 1000;

// run test with untyped property

class TestUntypedProperty {
    public $str = 'x';
}

$arr = [];
for ($i = 0; $i < 10000; $i++) {
    $arr[] = new TestUntypedProperty();
}
$serializedUntyped = serialize($arr);

$start = microtime(true);
for ($i = 0; $i < $runs; $i++) {
    unserialize($serializedUntyped);
}
$end = microtime(true);
echo sprintf("avg unserialize with untyped attribute: %.10f\n", ($end - $start) / $runs);


// run test with typed property

class Test__TypedProperty {
    public string $str = 'x';
}

$arr = [];
for ($i = 0; $i < 10000; $i++) {
    $arr[] = new Test__TypedProperty();
}
$serializedTyped = serialize($arr);

$start = microtime(true);
for ($i = 0; $i < $runs; $i++) {
    unserialize($serializedTyped);
}
$end = microtime(true);
echo sprintf("avg unserialize with typed attribute:   %.10f\n", ($end - $start)/$runs);
```

**Comment by c-locksmith** [comment]
Thanks @TysonAndre for the fix. I have tested the new version in our application and while I can confirm that the performance improved, about half of the reported slowdown still remains, which is still not quite enough for us to use this version in production, so we will remain on 3.2.9 for the moment.

Are there any hopes to get the performance roughly back to what it was before, even with the fixed type check?
