### ISSUE TITLE
pecl install igbinary -> Download of "pecl/igbinary" succeeded, but it is not a valid package archive

### ISSUE THREAD

**Issue by zeroasterisk** [igbinary/igbinary#38]
This is on a fresh install of Ubuntu 14.04.01 LTS

```
root@ubuntu:/opt/puppet# pecl install igbinary
downloading igbinary-1.2.1.tgz ...
Starting to download igbinary-1.2.1.tgz (36,869 bytes)
..........done: 36,869 bytes
could not extract the package.xml file from "/build/buildd/php5-5.5.9+dfsg/pear-build-download/igbinary-1.2.1.tgz"
Download of "pecl/igbinary" succeeded, but it is not a valid package archive
Error: cannot download "pecl/igbinary"
Download failed
install failed
```

**Comment by zeroasterisk** [comment]
Well, I was able to get around this with the following:

`pecl install -Z igbinary`

any idea why this might be?

**Comment by tricky** [comment]
Perhaps related to this?

https://bugs.launchpad.net/ubuntu/+source/php5/+bug/1310552

**Comment by zeroasterisk** [comment]
Yup - that sounds like it's probably the source of the problem -- sorry to bother you...  at least now it's documented so if anyone else searches for it they should have an easy workaround.

**Comment by tricky** [comment]
Very true, no bother. :)
