### ISSUE TITLE
Build Windows DLLs for PHP 8.3

### ISSUE THREAD

**Issue by TysonAndre** [igbinary/igbinary#386]
Related to #384

Include this in the next release

**Comment by juangacovas** [comment]
+1 Please release DLLs for PHP 8.3

**Comment by MacGritsch** [comment]
Anyone aware if PECL plans to bring its build-system back to create DLL files for Windows again?

**Comment by juangacovas** [comment]
> Anyone aware if PECL plans to bring its build-system back to create DLL files for Windows again?

There's been some request / awareness of the broken server on internals php list (see externals.io), but the "issue" seems stalled. Even some people offered hardware.

**Comment by Jan-E** [comment]
> Anyone aware if PECL plans to bring its build-system back to create DLL files for Windows again?

There are no plans. But there are some initiatives like:
https://phpext.phptools.online/extension/php/igbinary-210
https://github.com/php/php-sdk-binary-tools

**Comment by juangacovas** [comment]
> some initiatives like: https://phpext.phptools.online/extension/php/igbinary-210
Thanks, I didn't know of https://phpext.phptools.online being "a modern mirror of PECL website with Windows pre-build". I've even donated

**Comment by TysonAndre** [comment]
https://pecl.php.net/package/igbinary finally has DLLs for PHP 8.0-8.3 (e.g. 3.2.15) so I'm closing this.
