### ISSUE TITLE
Windows compatibility with apcu

### ISSUE THREAD

**Issue by fabicz** [igbinary/igbinary#44]
I've a setup of PHP 5.6.10 VC11 x64 TS, with APCu 4.0.7 and igbinary 1.1.1 - latest 5.6 compatible binary I found.

This setup breaks as long as I've 
apc.enabled=1

If I disable apc (apc.enabled=0) or remove igbinary extension, all runs fine.

I will be happy to retest if you provide me newer 5.6 x64 TS compatible version of igbinary.

**Comment by TysonAndre** [comment]
Could you be more specific about what part of the setup breaks? (Installing? Running? Running after long periods of times)

https://github.com/igbinary/igbinary/releases/tag/2.0.0 should be out on PECL in the near future, and it fixes installation (Tests worked in a Windows VM). Additionally, I recommend trying the latest APCU release.

https://github.com/igbinary/igbinary/blob/master/WINDOWS.md contains instructions to build igbinary from source

**Comment by fabicz** [comment]
I dont have this issue since I upgraded to PHP 7. Using igbinary together with apcu. I've the 
igbinary APC serializer ABI 	no

**Comment by TysonAndre** [comment]
Closing this, moving any further discussion to https://github.com/igbinary/igbinary/issues/37
