### ISSUE TITLE
Improve "igbinary_unserialize_header: unsupported version" message

### ISSUE THREAD

**Issue by phadej** [igbinary/igbinary#51]
Try to detect if
- wrong endianness
- looks like data serialised with php serialize

Note: Don't fallback, just inform about the possible cause. Silent fallbacks are dangerous.

**Comment by CybotTM** [comment]
the fallback doesn't need to be silent - you can still raise a warning.

And you can make configurable with default to off.

But how should i handle a failing session_start()?
Or foreign applications - which doen't have or implement this error-handling?

**Comment by phadej** [comment]
We don't want to increase internal igbinary complexity, just to account possible cases in transition period from `serialize` to `igbinary_serialize`.

If you run foreign application, run it with `igbinary` from the beginning.
Or kill all sessions in between, when you do a switch.

Please give a valid business case, most likely there are too many details that are better tackled with custom code (http://fi2.php.net/manual/en/function.session-set-save-handler.php).

**Comment by CybotTM** [comment]
probably your are right ... but i am not sure.

it would just made transition smoother ... clearing all data in large redis instances could be pain in the ass or serialized configuration structures.

i expected the fallback would be a 2-liner

**Comment by phadej** [comment]
We could argue about this. Why clear all data in large redis instances, when in cloud age we can just spawn new ones? At least you'll be sure there aren't old data anymore.

Serialised configuration structures is a bad idea. Use e.g. JSON for that, performance shouldn't be an issue.

If you really want to do transition with fallbackable serialisers, "righter" approach would be to create an extension which can try one or more unserialisers in order. This feature doesn't need to be in igbinary.

**Comment by CybotTM** [comment]
> Why clear all data in large redis instances, when in cloud age we can just spawn new ones?

Spawning new or clearing all is the same Problem: you will get empty caches - and this is something i want to prevent.

"bad", "righter" ... yes, you are absolutely right ... my problem is i have to work with real world application where i have limitations (like emptying caches must be avoided or configurations are stored in serializations).

as i wrote before: it would just make transition easier.
i cannot refactor whole apps (or the system environment and third part modules) at once, only parts of it.

I don't want to argue about this, do as you please, i just wanted to share my thoughts.

**Comment by phadej** [comment]
To decompose the problem:
- it's unfortunate that you cannot override session serialiser from php land, you have to write extension. Possible solutions:
  - fix PHP
  - make own extension (as I proposed already).
  - make a (temporary?) igbinary fork to help with transition, if it proves to be valuable and solid (well written, tests, exceptional cases handled), it can be merged upstream
- Killing all session data *once* shouldn't be a problem, your redis might die by itself too.
- Having session data & other data in the same backend is bad idea, I suggest you fix that. Even you aren't planning to switch to igbinary.

This is my personal rant: PHP applications have seen too much bad long-term design decisions, I don't want to make making new ones even easier.

**Comment by CybotTM** [comment]
> your redis might die by itself too.

[memcache(d)/Redis/couchabse] data can be persistant, sharded, aso.
If redis dies there would be a much worse problem.
If we just talk about caching (redis is much more than caching) - f. e. TYPO3 or magento will be no fun. Caching is not optional, it is a requirement - emptying caches could take down or at least slow down a page for a couple of hours - this can result in big losses of income or even user switching to other stores or portals.

> Having session data & other data in the same backend is bad idea

this is not the case.

> This is my personal rant: PHP applications have seen too much bad long-term design decisions, I don't want to make making new ones even easier.

PHP 6 was pulped - because there was no easy transition from PHP 5 to PHP 6. In PHP 7 every BC break (that is preventable) is nearly a stopper.
Easy transition has nothing to do with bad design.
You are just giving the users freedom of choice.

As you wrote before, we can argue about this - but we have some very different points of view.
I need to keep running websites while increasing performance and introduce new features.
You want to have a clean piece of software without looking back.

**Comment by CybotTM** [comment]
Anyway, thanks for igbinary! :-)

**Comment by edast** [comment]
can you throw exception when headers don't match? that way it would be easier to implement fallback - with try/catch block.

**Comment by tricky** [comment]
Possibly, perhaps as an option or a separate function. Doesn't directly solve session serialization though.

**Comment by edast** [comment]
Yes, but it is possible to have session serialization set to php native serialization from config.
