### ISSUE TITLE
Warning when unserialize a invalid string

### ISSUE THREAD

**Issue by mopahle** [igbinary/igbinary#55]
The following code:

``` php
<?php
igbinary_unserialize('test1234');
```

gives the PHP Warning " igbinary_unserialize_header: unsupported version: 1952805748, should be 1 or 2 in - on line 2".
Given the case that you cannot control what is in the string to unserialize, what is the correct way to prevent the warning? Is there a chance to validate the string before unserialize?

**Comment by phadej** [comment]
use
```php
@igbinary_unserialise('test1234')
```

There is no cheap way to validate the string, it would require it to parse it anyway. It might be a bit cheaper as there no need to build the result, but probably not much.

**Comment by TysonAndre** [comment]
A sanity check on the igbinary header is `stricmp('test1234', "\x00\x00\x00\x02") === 0 || stricmp('test1234', "\x00\x00\x00\x01") === 0` . Full validation is impossible without unserializing the string.
