### ISSUE TITLE
Compat with native unserialize()?

### ISSUE THREAD

**Issue by nicolas-grekas** [igbinary/igbinary#76]
Just wondering: what happens when doing `igbinary_unserialize(serialize('foo'))`?
Is `igbinary_unserialize()` able to autodetect the native serialization format and forward the call to the native `unserialize()` function?
If not, how about adding it to help moving forward, e.g. migrating sessions from `serialize` to `igbinary` without having to purge existing sessions in the process?

**Comment by TysonAndre** [comment]
Igbinary_unserialize(serialize(foo)) will never work.

The header of igbinary strings is "\x00\x00\x00\x02". Check for that in a customized save handler written in PHP (http://php.net/manual/en/function.session-set-save-handler.php) , or write a save handler/serializer extension depending on igbinary to do what was described.

It used to end in \x01 , and may become \x03 if a third format version is released

**Comment by TysonAndre** [comment]
See PS_SERIALIZER_DECODE_FUNC(igbinary) and PS_SERIALIZER_ENCODE_FUNC(igbinary) { in https://github.com/igbinary/igbinary/blob/master/src/php7/igbinary.c , as well as ext/session in php-src repo. PS_SERIALIZER_ENCODE_FUNC(php), I think.

**Comment by nicolas-grekas** [comment]
OK, thanks for the hints!
