### ISSUE TITLE
Stable release?

### ISSUE THREAD

**Issue by mente** [igbinary/igbinary#86]
It's been a while since last stable release 1.2.3. Does it make sense to start preparing stable release 2.0.0 with php7 support? Current master can be as an alpha version

**Comment by TysonAndre** [comment]
https://github.com/igbinary/igbinary7/issues/1 describes the same issue.

It makes sense to create 1.3.0 or 2.0.0, but I'm not a maintainer of the PECL repository.

**Comment by mente** [comment]
Who can do it? @phadej?

**Comment by phadej** [comment]
@TysonAndre 2.0.0 would be great. Could you prepare everything to make a release: i.e. push a `v2.0.0` tag, so I can upload it?

**Comment by TysonAndre** [comment]
@phadej Is the first pecl release a beta or stable release?

These 4 things would go in the 2.0.0 release, could you look at them, or should I just merge them? (Only non-test/documentation change is #89  , requested by @tricky in #51  )

Update changelog: https://github.com/igbinary/igbinary/pull/88
Improve "unsupported version" message: https://github.com/igbinary/igbinary/pull/89
Add forgotten test cases to package.xml: https://github.com/igbinary/igbinary/pull/90
Fix apcu unit test: https://github.com/igbinary/igbinary/pull/91

Final package.xml change: To be created

**Comment by TysonAndre** [comment]
@phadej - The tag `2.0.0` was pushed with everything that should be needed for a stable release supporting PHP 5.2 - 7.0. https://github.com/igbinary/igbinary/releases/tag/2.0.0

PHP 5.2 builds were failing before this because the macros for EXPECTED(expr) and UNEXPECTED(expr) did not exist in zend.h in 5.2 - Merged #96 and #94 to fix that, verified that php 5.2 tests passed locally.

A test was still missing from package.xml, this was merged #95 

#93 and #94 updated the version numbers throughout the codebase (docs and headers), and updated changelogs.

**Comment by mente** [comment]
Can #81 also be included in 2.0.0 release?

**Comment by TysonAndre** [comment]
Forgot about #97 

I was planning to put #81 in 2.0.1. I haven't tested it or benchmarked it yet

**Comment by phadej** [comment]
@TysonAndre should I still release 2.0.0 ?

**Comment by TysonAndre** [comment]
@phadej , release 2.0.0

The commit to use for 2.0.0 is https://github.com/igbinary/igbinary/commit/0bc3d483264ac7165a64e6e210e150375938ad58

This corresponds to the current github release https://github.com/igbinary/igbinary/releases/tag/2.0.0 (That had to be fixed, with bugs @mente pointed out (E.g. #97 was merged and 2.0.0 was already replaced) and bugs I noticed later).

#81 (The zend_string re-use) should go in 2.0.1. It's an improvement, has no API/header changes, and I don't see anything that would be likely to affect APCu.

**Comment by TysonAndre** [comment]
@phadej @tricky - could either of you add this to PECL?

The 2.0.0 tag hasn't changed since my last comment, no further changes are planned

**Comment by danydev** [comment]
@phadej @tricky @TysonAndre any update on this? are there blockers for the public PECL release?

**Comment by phadej** [comment]
http://pecl.php.net/package/igbinary/2.0.0

**Comment by phadej** [comment]
Now as I can see, @TysonAndre  is not in the maintaners list. Please, go ahead and add yourself.
