### ISSUE TITLE
php7.0.11 bug

### ISSUE THREAD

**Issue by kangtao10000** [igbinary/igbinary#98]
igbinary_unserialize_header: unsupported version: "Arra"..., should begin with a binary version header of "\x00\x00\x00\x01" or "\x00\x00\x00\x02"

**Comment by TysonAndre** [comment]
That's a bug in your program or setup.

Also, this issue doesn't contain php code to reproduce this.

**Comment by kangtao10000** [comment]
example:
 _redis->setOption(\Redis::OPT_SERIALIZER, \Redis::SERIALIZER_IGBINARY);
_redis->set('key',['name'=>'test',age=2]);
Do not support,before the support of the.

**Comment by kangtao10000** [comment]
Thank you,the problem is solved,because the version of the igbinayr.

**Comment by TysonAndre** [comment]
Aside, for anyone having similar problems with PHPRedis

PHPRedis has a patch to detect non-igbinary data in php 5, but not in php 7. It is on the `develop` branch, but not the `php7` branch. See https://github.com/phpredis/phpredis/pull/761#issuecomment-203957334

The maintainer(s) of phpredis seem to be gradually patching the `develop` (php 5) branch to compile under php 7 as well (with `#ifdef`). I assume this will take weeks/months
