### ISSUE TITLE
CI for Windows builds

### ISSUE THREAD

**Issue by TysonAndre** [igbinary/igbinary#99]
Do any other igbinary devs want to add this?

https://www.appveyor.com/ is like Travis CI, but supports building on Windows environments.

> Free for open-source projects. Plans start from $29/month.

https://github.com/phalcon/zephir/blob/master/appveyor.yml is an example of a module using appveyor.

**Comment by tricky** [comment]
An excellent step, windows testing is lacking.

Besides, I never object to additional testing or CI when it's just a matter of a simple recipe file.

**Comment by TysonAndre** [comment]
Ok, I'll look at setting it up tomorrow.

**Comment by TysonAndre** [comment]
@tricky - AppVeyor builds work.

However, they need web hooks set up in the github repo's settings(which I can't access) in order to automatically build pushes to master and PRs. See http://help.appveyor.com/discussions/questions/203-auto-run-tests-on-pull-requests

I sent you the appveyor web hook URL in an email.

**Comment by TysonAndre** [comment]
Added https://github.com/igbinary/igbinary/pull/102 so that `nmake test` failures would show up properly.
